In [2]:
from bs4 import BeautifulSoup
from urllib.request import urlopen
import os
import re

In [3]:
url = "http://www.freeos.com/guides/lsst/"
html_fname = os.path.join(os.getcwd(),'linux_guide.html')
os.getcwd()

'C:\\Users\\anipatel'

In [4]:
import numpy as np

In [7]:
arr_one_dim = np.array([10,20,30])
print(arr_one_dim)

[10 20 30]


In [9]:
arr_two_dim = np.array([[2,4,7,8],[1,9,5,3]])
print(arr_two_dim)

[[2 4 7 8]
 [1 9 5 3]]


In [11]:
print('Type - ',type(arr_one_dim))
print('Shape - ',arr_two_dim.shape)

Type -  <class 'numpy.ndarray'>
Shape -  (2, 4)


In [12]:
arr_0 = np.zeros((3,6), dtype = np.int64)
print(arr_0)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [13]:
arr_1 = np.ones((3,2), dtype = np.int64)
print(arr_1)

[[1 1]
 [1 1]
 [1 1]]


In [18]:
arr_all = np.full((2,4),1.4)
print(arr_all)

[[1.4 1.4 1.4 1.4]
 [1.4 1.4 1.4 1.4]]


In [20]:
arr_eye = np.eye(3)
print(arr_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
arr_random = np.random.random((3,3))
print(arr_random)

[[0.47931847 0.84232157 0.38829689]
 [0.73180561 0.95036672 0.79350348]
 [0.37873835 0.84092969 0.68476841]]


In [24]:
arr_randint = np.random.randint(200, size=(4,3))
print(arr_randint)

[[117 104 151]
 [109 117 125]
 [ 96  67 128]
 [199 118  63]]


In [29]:
arr_arange = np.arange(1,10,2)
print(arr_arrange)

[1 3 5 7 9]


In [31]:
arr_tile = np.tile(arr_arange, (2,3))
print(arr_tile, '-', arr_tile.shape)

[[1 3 5 7 9 1 3 5 7 9 1 3 5 7 9]
 [1 3 5 7 9 1 3 5 7 9 1 3 5 7 9]] - (2, 15)


In [33]:
#Slicing
arr = np.array([[1,4,6,4],[3,6,2,8],[9,0,3,1]])
print(arr)

[[1 4 6 4]
 [3 6 2 8]
 [9 0 3 1]]


In [37]:
print(arr[:3,2:])

[[6 4]
 [2 8]
 [3 1]]


In [38]:
print(arr[:3,1])

[4 6 0]


In [39]:
print(arr[1:2,1:2])

[[6]]


In [40]:
arr[0,0]=18
arr

array([[18,  4,  6,  4],
       [ 3,  6,  2,  8],
       [ 9,  0,  3,  1]])

In [41]:
#Interger Array Indexing
row_idx = [0,1,2,1]
col_idx = [1,0,2,1]
print(list(zip(row_idx,col_idx)))

[(0, 1), (1, 0), (2, 2), (1, 1)]


In [43]:
arr_idx_1 = arr[row_idx, col_idx]
print(arr_idx_1)

[4 3 3 6]


In [45]:
arr_idx_2 = np.array([arr[0,1], arr[2,0], arr[2,3]])
print(arr_idx_2)

[4 9 1]


In [49]:
#Dynamymic
arr_indexes = [0,2,1]
arr_idx_3 = arr[np.arange(3), arr_indexes]
print(arr_idx_3)

[18  2  0]


In [50]:
arr-=6
print(arr)

[[12 -2  0 -2]
 [-3  0 -4  2]
 [ 3 -6 -3 -5]]


In [51]:
#Boolean Array Indexing
print(arr<1)

[[False  True  True  True]
 [ True  True  True False]
 [False  True  True  True]]


In [57]:
print(arr[(arr>0) & (arr<10)])

[2 3]


In [59]:
#Mathematical Operations 
arr1 = np.array([[1,3],[2,5]])
arr2 = np.array([[2,4],[1,0]])
print(arr1 , "\n\n" , arr2)

[[1 3]
 [2 5]] 

 [[2 4]
 [1 0]]


In [60]:
#addition
print(arr1+arr2, "\n\n")
print(np.add(arr1,arr2))

[[3 7]
 [3 5]] 


[[3 7]
 [3 5]]


In [64]:
#Subtraction => arr2 - arr1 or 
print(np.subtract(arr2,arr1),"\n")

#multiplication  => arr2*arr1 or
print(np.multiply(arr2, arr1),"\n")

[[ 1  1]
 [-1 -5]] 

[[ 2 12]
 [ 2  0]] 



In [67]:
# Division => arr1/arr2 or
print(np.divide(arr1,arr2),"\n")

#Modulus => arr1%arr2 or 
print(np.mod(arr2,arr1),"\n")

[[0.5  0.75]
 [2.    inf]] 

[[0 1]
 [1 0]] 



<ipython-input-67-e504a9428fd2>:2: RuntimeWarning: divide by zero encountered in true_divide
  print(np.divide(arr1,arr2),"\n")


In [68]:
#sqrt
print(np.sqrt(arr2))

[[1.41421356 2.        ]
 [1.         0.        ]]


In [69]:
#Dot Function = > Matrix Multiplication
print(np.dot(arr1,arr2))

[[5 4]
 [9 8]]


In [70]:
print(np.sum(arr1))

11


In [71]:
print(np.sum(arr1, axis =0)) #axis = 1

[3 8]


In [73]:
#transpose
print(arr1.T)

[[1 2]
 [3 5]]


In [75]:
#Broadcasting
print(arr, "\n")
arr_1 = [2,4,0,1]
print(arr_1, "\n")

print(arr.shape, "\n")
print(np.tile(arr_1,(arr.shape[0],1)))

[[12 -2  0 -2]
 [-3  0 -4  2]
 [ 3 -6 -3 -5]] 

[2, 4, 0, 1] 

(3, 4) 

[[2 4 0 1]
 [2 4 0 1]
 [2 4 0 1]]


In [76]:
print(arr+arr_1)

[[14  2  0 -1]
 [-1  4 -4  3]
 [ 5 -2 -3 -4]]


In [79]:
#Reshape
arr = np.array(list(range(1,80,3)))
print(arr, '-', arr.shape, "-", len(arr))

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70
 73 76 79] - (27,) - 27


In [81]:
print("Reshape - \n", arr.reshape(3,9))

Reshape - 
 [[ 1  4  7 10 13 16 19 22 25]
 [28 31 34 37 40 43 46 49 52]
 [55 58 61 64 67 70 73 76 79]]


In [83]:
print("Reshape 1 - \n ", arr.reshape(3,3,3,1))

Reshape 1 - 
  [[[[ 1]
   [ 4]
   [ 7]]

  [[10]
   [13]
   [16]]

  [[19]
   [22]
   [25]]]


 [[[28]
   [31]
   [34]]

  [[37]
   [40]
   [43]]

  [[46]
   [49]
   [52]]]


 [[[55]
   [58]
   [61]]

  [[64]
   [67]
   [70]]

  [[73]
   [76]
   [79]]]]


In [84]:
# Concatenating the Arrays
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(np.concatenate((arr1, arr2)))

[1 2 3 4 5 6]


In [86]:
print(np.stack((arr1, arr2), axis=1)) # axis=0

[[1 4]
 [2 5]
 [3 6]]


In [87]:
#Concatenating 2D Arrays
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[6,4],[2,8]])

print(np.concatenate((arr1,arr2), axis = 1))

[[1 2 6 4]
 [3 4 2 8]]


In [89]:
#Split the array to multiple arrays
arr = np.array([1,3,4,6,2,7,8,6,9])
arr_splitted = np.array_split(arr,6)
print(arr_splitted)
print("1st ", arr_splitted[0])
print("2nt ", arr_splitted[1])
print("3rt ", arr_splitted[2])
print("4th ", arr_splitted[3])
print("5th ", arr_splitted[4])
print("6th ", arr_splitted[5])

[array([1, 3]), array([4, 6]), array([2, 7]), array([8]), array([6]), array([9])]
1st  [1 3]
2nt  [4 6]
3rt  [2 7]
4th  [8]
5th  [6]
6th  [9]


In [91]:
#Split the 2D array to multiple arrays
arr = np.array([[1,3],[4,6],[2,7],[8,6],[9,1]])
arr_splitted = np.array_split(arr,4)
print(arr_splitted)

[array([[1, 3],
       [4, 6]]), array([[2, 7]]), array([[8, 6]]), array([[9, 1]])]


In [94]:
#searching for the particular element
arr_rearched = np.where(arr>6)
print(arr)
print(arr_rearched)

[[1 3]
 [4 6]
 [2 7]
 [8 6]
 [9 1]]
(array([2, 3, 4], dtype=int64), array([1, 0, 0], dtype=int64))


In [95]:
print(np.where(arr>=6, arr-4,arr))

[[1 3]
 [4 2]
 [2 3]
 [4 2]
 [5 1]]


In [ ]:
import socket

# take the server name and port name
host = 'local host'
port = 5000

# create a socket at server side
# using TCP / IP protocol
s = socket.socket(socket.AF_INET,
				socket.SOCK_STREAM)

# bind the socket with server
# and port number
s.bind(('', port))

# allow maximum 1 connection to
# the socket
s.listen(1)

# wait till a client accept
# connection
c, addr = s.accept()

# display client address
print("CONNECTION FROM:", str(addr))

# send message to the client after
# encoding into binary string
c.send(b"HELLO, How are you ? \
	Welcome to Akash hacking World")

msg = "Bye.............."
c.send(msg.encode())

# disconnect the server
c.close()


In [ ]:
import socket

# take the server name and port name

host = 'local host'
port = 5000

# create a socket at client side
# using TCP / IP protocol
s = socket.socket(socket.AF_INET,
				socket.SOCK_STREAM)

# connect it to server and port
# number on local computer.
s.connect(('127.0.0.1', port))

# receive message string from
# server, at a time 1024 B
msg = s.recv(1024)

# repeat as long as message
# string are not empty
while msg:
	print('Received:' + msg.decode())
	msg = s.recv(1024)

# disconnect the client
s.close()
